name: Upload bugfix 

on:
  workflow_dispatch:
  push:
    branches:
      - woof/bugfix

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.WOOF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WOOF_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build site
        run: yarn run build
        env:
          VITE_MAINNET_URL: ${{ vars.VITE_MAINNET_URL }}
          VITE_ARBITRUM_URL: ${{ vars.VITE_ARBITRUM_URL }}
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_OPTIMISM_URL: ${{ vars.VITE_OPTIMISM_URL }}
          VITE_POLYGON_URL: ${{ vars.VITE_POLYGON_URL }}
          VITE_SCROLL_URL: ${{ vars.VITE_SCROLL_URL }}
          VITE_LINEA_URL: ${{ vars.VITE_LINEA_URL }}
          VITE_MANTLE_URL: ${{ vars.VITE_MANTLE_URL }}
          VITE_UNICHAIN_URL: ${{ vars.VITE_UNICHAIN_URL }}
          VITE_V3_API_HOST: ${{ vars.VITE_V3_API_HOST }}

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://compound-related-bugfix/ --delete

      - name: CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.WOOF_BUGFIX_AWS_DISTRIBUTION_ID }} --paths "/*"
